### ISSUE TITLE
Log the request in case it is denied

### ISSUE THREAD

**Issue by scatrin** [StyraInc/opa-kafka-plugin#54]
It would be useful to have an option to log all requests that get access denied from OPA.

**Comment by anderseknert** [comment]
HI @scatrin! 👋 🇸🇪 Since the authorization decision is delegated to OPA, that's normally where you'll want to log it. Have you looked into the OPA [decision logging](https://www.openpolicyagent.org/docs/latest/management-decision-logs/) capabilities? With that enabled, you'd commonly only want to know about (and log) errors in the client, i.e. cases where no proper "decision" was taken and OPA had nothing to log.

I guess it still could make sense to log *something* in the client on decisions, and I would not mind having that added as long as it's easy to disable, as I'd imagine those logs would get quite noisy. The question would be what level to log at by default, and what data to include.

**Comment by scatrin** [comment]
Ooh nice, that looks like what I need. I was digging through the OPA docs but somehow I missed that. Thanks 🇸🇪

**Comment by anderseknert** [comment]
Hi @scatrin! How's you OPA - Kafka integration working out? 🙂
Do you still feel like the plugin should log more, or was decision logging the answer?
